# Generated by Django 4.1.3 on 2022-11-19 14:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='item name')),
                ('description', models.TextField(verbose_name='description')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0.01, 'Цена не может быть ниже 0,01 руб.')], verbose_name='price')),
            ],
            options={
                'verbose_name': 'item',
                'verbose_name_plural': 'items',
                'ordering': ('price',),
            },
        ),
    ]
